### ISSUE TITLE
Update on pypi

### ISSUE THREAD

**Issue by C4ptainCrunch** [kennethreitz/inbox.py#11]
Hey !

The package haven't been updated in pypi since more than an year and the readme on github does not correspond with the package (no subject support in the old version). It would be great to have an up to date version to use with pip :)

Thx :)

**Comment by C4ptainCrunch** [comment]
Looks like `inbox` has been used for something else: https://pypi.python.org/pypi/inbox

**Comment by alanhamlett** [comment]
https://pypi.python.org/pypi/inbox.py
